# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/University/Junior/FPGA/Snake_Game_V3/snake_game/snake_game.srcs/sources_1/ip/clk_wiz_vga/clk_wiz_vga.xci
# IP: The module: 'clk_wiz_vga' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/University/Junior/FPGA/Snake_Game_V3/snake_game/snake_game.gen/sources_1/ip/clk_wiz_vga/clk_wiz_vga_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_vga'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/University/Junior/FPGA/Snake_Game_V3/snake_game/snake_game.gen/sources_1/ip/clk_wiz_vga/clk_wiz_vga.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_vga'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/University/Junior/FPGA/Snake_Game_V3/snake_game/snake_game.gen/sources_1/ip/clk_wiz_vga/clk_wiz_vga_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_vga'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/University/Junior/FPGA/Snake_Game_V3/snake_game/snake_game.srcs/sources_1/ip/clk_wiz_vga/clk_wiz_vga.xci
# IP: The module: 'clk_wiz_vga' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/University/Junior/FPGA/Snake_Game_V3/snake_game/snake_game.gen/sources_1/ip/clk_wiz_vga/clk_wiz_vga_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_vga'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/University/Junior/FPGA/Snake_Game_V3/snake_game/snake_game.gen/sources_1/ip/clk_wiz_vga/clk_wiz_vga.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_vga'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/University/Junior/FPGA/Snake_Game_V3/snake_game/snake_game.gen/sources_1/ip/clk_wiz_vga/clk_wiz_vga_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_vga'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
